# Generated by Django 5.2.17 on 2026-09-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('Movie', 'Movie'), ('TV Show', 'TV Show'), ('Book', 'Book'), ('Video Game', 'Video Game'), ('Music', 'Music')], max_length=20)),
                ('genre', models.CharField(max_length=100)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('personal_rating', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Owned', 'Owned')], max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
