# Generated by Django 5.2.17 on 2026-10-08 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('Movie', 'Movie'), ('TV Show', 'TV Show'), ('Book', 'Book'), ('Video Game', 'Video Game'), ('Music', 'Music')], max_length=20)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('personal_rating', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Owned', 'Owned')], default='Planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
